# Generated by Django 3.0.6 on 2020-08-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categories',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory',
            new_name='name',
        ),
    ]
